### ISSUE TITLE
Protected workloads shows 0

### ISSUE THREAD

**Issue by Chebbles** [VeeamHub/veeam-healthcheck#18] opened 2023-07-04 10:45 UTC
When scanning a platform which consists of 14 VBR servers of a service provider vor various Customers, the Protected workloads for all the HC reports are 0 (zero).
This is goes for all workload on all customers.

The Job session reports do have the virtual machines listed correctly in the reports.

Expected behaviour is that we'd correctly get an overview of the protected workloads.

![image](https://github.com/VeeamHub/veeam-healthcheck/assets/11082890/498bc115-5d47-4fc9-88c1-18fbdbf5f422)

**Comment by adamcongdon** [comment] 2023-07-12 13:10
Hi,

Which version of the vHC was this generated? There are some cases where the PowerShell script is failing in certain scenarios that I am still working to pin down. I've improved logging & error handling to hopefully ID the root cause. However, I cannot reproduce the situation in my labs.

Which of the workloads do you have, and which do you not have?

Also, if you're able to share the log, please send me the files in C:\temp\vHC\Original\Log\.

**Comment by Chebbles** [comment] 2023-07-15 22:28
Im missing VM, and plugin workloads. afaik no agent workloads on the systems.
I'll share the all results with you.

**Comment by adamcongdon** [comment] 2024-08-24 02:37
This should be resolved in the latest release.

**Closed by adamcongdon** 2024-08-24 02:37 UTC
